CREATE TABLE [Student] (
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(120) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Document] NVARCHAR(20) NULL,
    [BirthDate] DATETIME NULL,
    [CreateDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Student PRIMARY KEY ([Id])
)
GO