CREATE TABLE [Author] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(80) NOT NULL,
	[Title] NVARCHAR(80) NOT NULL,
	[Image] NVARCHAR(1024) NOT NULL,
	[Bio] NVARCHAR(2000) NOT NULL,
	[Url] NVARCHAR(450) NULL,
	[Email] NVARCHAR(160) NOT NULL,
	[Type] TINYINT NOT NULL,
	CONSTRAINT [PK_Author] PRIMARY KEY ([Id])
)
GO

CREATE TABLE [Career] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(160) NOT NULL,
	[Summary] NVARCHAR(2000) NOT NULL,
	[Url] NVARCHAR(1024) NOT NULL,
	[DurationInMinutes] INT NOT NULL,
	[Active] BIT NOT NULL,
	[Featured] BIT NOT NULL,
	[Tags] NVARCHAR(160) NOT NULL,
	CONSTRAINT [PK_Career] PRIMARY KEY ([Id])
)
GO

CREATE TABLE [Category] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(160) NOT NULL,
	[Url] NVARCHAR(1024) NOT NULL,
	[Summary] NVARCHAR(2000) NOT NULL,
	[Order] INT NOT NULL,
	[Description] TEXT NOT NULL,
	[Featured] BIT NOT NULL,
	CONSTRAINT [PK_Category] PRIMARY KEY ([Id])
)
GO

CREATE TABLE [Course] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Tag] NVARCHAR(20) NOT NULL,
	[Title] NVARCHAR(160) NOT NULL,
	[Summary] NVARCHAR(2000) NOT NULL,
	[Url] NVARCHAR(1024) NOT NULL,
	[Level] TINYINT NOT NULL,
	[DurationInMinutes] INT NOT NULL,
	[CreateDate] DATETIME NOT NULL,
	[LastUpdateDate] DATETIME NOT NULL,
	[Active] BIT NOT NULL,
	[Free] BIT NOT NULL,
	[Featured] BIT NOT NULL,
	[AuthorId] UNIQUEIDENTIFIER NOT NULL,
	[CategoryId] UNIQUEIDENTIFIER NOT NULL,
	[Tags] NVARCHAR(160) NOT NULL,
	CONSTRAINT [PK_Course] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Course_Author] FOREIGN KEY ([AuthorId]) REFERENCES [Author] ([Id]),
	CONSTRAINT [FK_Course_Category] FOREIGN KEY ([CategoryId]) REFERENCES [Category] ([Id])
)
GO

CREATE TABLE [CareerItem] (
	[CareerId] UNIQUEIDENTIFIER NOT NULL,
	[CourseId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(160) NOT NULL,
	[Description] TEXT NOT NULL,
	[Order] TINYINT NOT NULL,
	CONSTRAINT [PK_CareerItem] PRIMARY KEY ([CareerId],[CourseId]),
	CONSTRAINT [FK_CareerItem_Course] FOREIGN KEY ([CourseId]) REFERENCES [Course] ([Id]),
	CONSTRAINT [FK_CareerItem_Career] FOREIGN KEY ([CareerId]) REFERENCES [Career] ([Id])
)
GO

CREATE TABLE [StudentCourse] (
	[StudentId] UNIQUEIDENTIFIER NOT NULL,
	[CourseId] UNIQUEIDENTIFIER NOT NULL,
	[Progress] TINYINT NOT NULL,
	[Favorite] BIT NOT NULL,
	[StartDate] DATETIME NOT NULL ,
	[LastUpdateDate] DATETIME NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_StudentCourse] PRIMARY KEY ([StudentId],[CourseId]),
	CONSTRAINT [FK_StudentCourse_Student] FOREIGN KEY ([StudentId]) REFERENCES [Student] ([Id]),
	CONSTRAINT [FK_StudentCourse_Course] FOREIGN KEY ([CourseId]) REFERENCES [Course] ([Id])
)
GO