CREATE OR ALTER PROCEDURE spDeleteStudent
(
	@StudentId UNIQUEIDENTIFIER
)
AS
BEGIN
	BEGIN TRANSACTION
		DELETE FROM StudentCourse WHERE StudentId = @StudentId
		DELETE FROM Student WHERE Id = @StudentId

	COMMIT
END
GO

EXEC spDeleteStudent '014B38ED-C48C-4A3C-B9CF-EC9F00973017'